
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - simple-wordpress.simplewordpress.com
  resources:
  - simplewordpresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - simple-wordpress.simplewordpress.com
  resources:
  - simplewordpresses/finalizers
  verbs:
  - update
- apiGroups:
  - simple-wordpress.simplewordpress.com
  resources:
  - simplewordpresses/status
  verbs:
  - get
  - patch
  - update
