# permissions for end users to view simplewordpresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: simplewordpress-viewer-role
rules:
- apiGroups:
  - simple-wordpress.simplewordpress.com
  resources:
  - simplewordpresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - simple-wordpress.simplewordpress.com
  resources:
  - simplewordpresses/status
  verbs:
  - get
